### ISSUE TITLE
Wasn't clear how to select the repos

### ISSUE THREAD

**Issue by arisacoba** [adrianmg/github-pewpew#31]
On my initial tries, it wasn't clear how to select the repos. My initial gut was to press enter to select the repos. However, I guess the `enter` function would run the process already. In the end, I don't get to select the repos (ends up with the screenshot below). I ended up typing the whole text: my username + repo name to make it work instead

<img width="386" alt="image" src="https://user-images.githubusercontent.com/8143661/161487531-88f5bbe3-5e39-4954-8e5d-68b4205e2e7c.png">

Maybe there can be an instruction or obvious way to select the repos (From the Issues here, I just learned you need to use `space` to select the repos). `Enter` seems to be the obvious way to select and maybe multi-selection is a secondary feature? (like requires additional key + enter) Just throwing random ideas

Overall, love this package 🎉

**Comment by adrianmg** [comment]
Thanks for reporting @arisacoba !

**Comment by arisacoba** [comment]
Just wanna check back here that it is still not intuitive enough for me that `space` selects the repo. For a first-time user or returning user, I had to go back to this Issue to know how to select the repo I want to delete 😬 

Maybe a little instruction in the CLI helps?

Sample of multiple tries with no repos selected. Getting me frustrated and all lol
<img width="996" alt="image" src="https://user-images.githubusercontent.com/8143661/183851423-5ba0094c-9007-4fb7-ae14-b6a3a1961abc.png">

**Comment by adrianmg** [comment]
Fixed here: https://github.com/adrianmg/github-pewpew/pull/37/commits/5db9794cb8c98e0736ee7939b2e911104d12186f

**Comment by arisacoba** [comment]
Thank you for the hint!
